spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/dbpic?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: h@1j33=q
      driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

